apiVersion: apps/v1
kind: Deployment
metadata:
  name: poliza-service
  namespace: siniestros
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poliza-service
  template:
    metadata:
      labels:
        app: poliza-service
    spec:
      containers:
      - name: poliza
        image: santiagoarroyo/poliza:latest
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-poliza:3306/polizadb?createDatabaseIfNotExist=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-poliza-secret
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /api/polizas
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/polizas
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: poliza-service
  namespace: siniestros
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: poliza-service
