apiVersion: apps/v1
kind: Deployment
metadata:
  name: siniestro-service
  namespace: siniestros
spec:
  replicas: 2
  selector:
    matchLabels:
      app: siniestro-service
  template:
    metadata:
      labels:
        app: siniestro-service
    spec:
      containers:
      - name: siniestro
        image: santiagoarroyo/siniestro:latest
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-siniestro:5432/siniestrodb"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: postgres-siniestro-config
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-siniestro-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 8083
        livenessProbe:
          httpGet:
            path: /api/siniestros
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/siniestros
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: siniestro-service
  namespace: siniestros
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
  selector:
    app: siniestro-service
